### ISSUE TITLE
Labels are slightly cut in the Venn Diagram

### ISSUE THREAD

**Issue by bhaibeka** [bhklab/PharmacoDB#8] opened 2017-09-05 16:38 UTC
See CTRPv2 label in http://pharmacodb.pmgenomics.ca/search?q=ctrpv2+gdsc1000+gcsi

**Comment by kofiav** [comment] 2017-09-05 17:09
Are you using Chrome? 
I can't reproduce the issue in the most up to date version of PharmacoDB

**Comment by kofiav** [comment] 2017-09-05 17:09
See: http://opennet-33-51.uhnres.utoronto.ca:3001/search?q=ctrpv2+gdsc1000+gcsi

**Comment by kofiav** [comment] 2017-09-11 01:45
Issue has been fixed as of latest deployment.

**Closed by kofiav** 2017-09-11 01:45 UTC
Labels: user-interface
